-- =============================================================================
-- V3 — Transactional outbox for the ingestion domain events.
-- OutboxPublisher polls unpublished rows (published = false) ordered by
-- created_at and emits them to Kafka (inventory.ingestion.completed/.failed).
-- This table was missing from V1, so the poller failed with
--   relation "ingestion_db.outbox" does not exist
-- and no ingestion.completed events were ever produced. Columns mirror
-- entity OutboxEvent. IF NOT EXISTS so it is safe where the table was already
-- created out-of-band on a running environment.
-- =============================================================================
SET search_path TO ingestion_db;

CREATE TABLE IF NOT EXISTS outbox (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id UUID         NOT NULL,
    event_type   VARCHAR(100) NOT NULL,
    payload      JSONB        NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    published_at TIMESTAMP,
    published    BOOLEAN      NOT NULL DEFAULT FALSE
);

-- Poller filters on unpublished rows in insertion order.
CREATE INDEX IF NOT EXISTS idx_outbox_unpublished ON outbox(created_at) WHERE published = FALSE;
