server:
  port: 8083

spring:
  application:
    name: product-catalog-service
  datasource:
    url: jdbc:mysql://localhost:3306/insightflow_catalog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true