server:
  port: 8082

spring:
  application:
    name: data-ingestion-service
  datasource:
    url: jdbc:mysql://localhost:3306/insightflow_ingestion?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ingestion-group-v3
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

catalog-service:
  base-url: http://localhost:8083
  spring:
    threads:
      virtual:
        enabled: true