-- =============================================================================
-- V1 — AI recommendation output.
-- recommendation_histories: one row per AI run (status + raw result), the table
--   the service actually reads/writes. ai_recommendations: latest-result table.
-- Both are tenant-scoped; reads are filtered by tenant_id.
-- =============================================================================
SET search_path TO recommendation_db;

CREATE TABLE recommendation_histories (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             VARCHAR(36)  NOT NULL,
    workspace_id          VARCHAR(36)  NOT NULL,
    status                VARCHAR(20),                -- PROCESSING, DONE, ERROR
    recommendation_result TEXT,
    error_log             TEXT,
    created_at            TIMESTAMPTZ,
    updated_at            TIMESTAMPTZ
);
CREATE INDEX idx_rec_histories_tenant    ON recommendation_histories(tenant_id);
CREATE INDEX idx_rec_histories_workspace ON recommendation_histories(workspace_id);

CREATE TABLE ai_recommendations (
    id                  VARCHAR(36) PRIMARY KEY,
    tenant_id           VARCHAR(36) NOT NULL,
    workspace_id        VARCHAR(36) NOT NULL,
    recommendation_json TEXT,
    status              VARCHAR(20) NOT NULL,
    error_log           TEXT,
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_ai_recommendations_workspace UNIQUE (workspace_id)
);
CREATE INDEX idx_ai_recommendations_tenant ON ai_recommendations(tenant_id);
