-- =============================================================================
-- V3 — Transactional outbox for workspace domain events.
-- OutboxPublisher polls unpublished rows (published = false) ordered by
-- created_at and emits them to Kafka. Columns mirror entity OutboxEvent:
--   id BIGINT IDENTITY, aggregate_id UUID, event_type, payload (jsonb),
--   created_at, published_at, published.
-- =============================================================================
SET search_path TO workspace_db;

CREATE TABLE outbox (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id UUID         NOT NULL,
    event_type   VARCHAR(100) NOT NULL,
    payload      JSONB        NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    published_at TIMESTAMP,
    published    BOOLEAN      NOT NULL DEFAULT FALSE
);

-- Poller filters on unpublished rows in insertion order.
CREATE INDEX idx_outbox_unpublished ON outbox(created_at) WHERE published = FALSE;
