server:
  port: 8081

spring:
  application:
    name: user-workspace-service
  datasource:
    url: jdbc:mysql://localhost:3306/insightflow_workspace?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

aws:
  s3:
    bucket: insightflow-bucket
    region: ap-southeast-1
    presign-expiration-minutes: 15